### ISSUE TITLE
DC motor to become a linear actuator ("pusher")

### ISSUE THREAD

**Issue by SilviyaGIvanova** [Pschiee/Perfect-Colour#13]
How should the DC motor be mounted so that it pushes against the syringe to dispense paint? Initial design does not seem to account for this because the motor itself would spin instead of going up and down.

**Comment by SilviyaGIvanova** [comment]
This is done through a threaded plate which is held onto the top plate of the structure via screw rods. As the motor spins the threaded rod it acts as a linear actuator and moves up and down (pushing against the syringe to dispense paint). The motor itself is constrained from spinning as it is placed between two aluminium plates which only allow it to slide.
![57044372_601231833728858_6013923966475829248_n](https://user-images.githubusercontent.com/48563042/56095318-56ddd600-5ed3-11e9-84b9-0ff9e4c06445.jpg)

**Comment by LeireFroufe** [comment]
It works efficiently

**Comment by SilviyaGIvanova** [comment]
![57044372_601231833728858_6013923966475829248_n](https://user-images.githubusercontent.com/48563042/56095310-47f72380-5ed3-11e9-9c53-9f50fae94b7c.jpg)
