### ISSUE TITLE
Rotations Inaccurate

### ISSUE THREAD

**Issue by LeireFroufe** [Pschiee/Perfect-Colour#26]
The syringes are not ending up underneath the DC motor on each rotation.

**Comment by Pschiee** [comment]
A mechanical issue. Software is fine.

**Comment by LeireFroufe** [comment]
Carousel had come loose, so it was rotating without the motor. Therefore going to wrong positions. It has been tightened.

**Comment by LeireFroufe** [comment]
It now works. Small rotation due to surface area of the pusher being too small and sliding through the top of the syringe. We increased the surface area.

It works.
