### ISSUE TITLE
Initial PCB design - fine but not optimal

### ISSUE THREAD

**Issue by SilviyaGIvanova** [Pschiee/Perfect-Colour#8]
Separate PCBs were designed for the testing stage of the project, however, the team needed a PCB that would fit as a hat on the Raspberry Pi and would have similar dimensions. This would make the design more compact and appealing to the eye. Could everything fit on the bottom so it is hidden?

**Comment by Pschiee** [comment]
It would be optimal if everything could be put on the one side however with the number of different components required on the board, this isn't going to be possible

**Comment by SilviyaGIvanova** [comment]
This has been done (double-sided PCB was manufactured) and testing has begun.
