### ISSUE TITLE
Stepper motor does not turn

### ISSUE THREAD

**Issue by SilviyaGIvanova** [Pschiee/Perfect-Colour#9]
Stepper motor was tested on the final PCB. Turned for a while then started turning forwards and backwards for no reason (?). Issue might be with the new PCB.

**Comment by SilviyaGIvanova** [comment]
PCB has been checked. Nothing is causing a short-circuit.
Test motor on old PCB to make sure it is still working.

**Comment by Pschiee** [comment]
Problem was on enable pin A. There was a thin track connecting this to ground and therefore half of the pins were disabled.
